# Generated by Django 4.2.6 on 2023-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='resim',
            field=models.FileField(upload_to='profiles/', verbose_name='Profil Resmi'),
        ),
    ]