# Generated by Django 4.2.6 on 2023-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profiles_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('foto', models.FileField(upload_to='kullanicilar/', verbose_name='Profil Fotoğrafı')),
                ('tel', models.IntegerField(default=0)),
                ('dogum', models.DateField()),
            ],
        ),
    ]