# Generated by Django 4.2.6 on 2024-01-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_kullanici_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='user',
        ),
        migrations.AddField(
            model_name='kullanici',
            name='resim',
            field=models.FileField(default='exit', upload_to='kullanicilar/', verbose_name='Profil Resmi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]